### ISSUE TITLE
plugin setup should be used instead of config

### ISSUE THREAD

**Issue by franzholz** [romm/formz_example#9]
The extension extends the "config" setup. However "plugin" must be used here.

see https://docs.typo3.org/typo3cms/ExtbaseFluidBook/b-ExtbaseReference/Index.html

    config.tx_formz {

should be

    plugin.tx_formz {

**Comment by romm** [comment]
Actually, this is not how it is supposed to work.

The TypoScript in these files only has a declarative job, mostly because the form could be used both in the frontend and in the TYPO3 backend. When FormZ will reach this configuration, it will make no distinction about where the form definition comes from.

You can see the [TypoScriptService](https://github.com/romm/formz/blob/1.2.0/Classes/Service/TypoScriptService.php#L28) for more information about it.

I leave the ticket opened for the moment, please answer if you want to add something more on this topic. 😉

**Comment by franzholz** [comment]
As fas as I understand the TypoScript Setup, the config is reserved for TYPO3, where plugin is used for extensions. I have never seen any extension which introduces a new config setup. It seems that extbase does this, but it is a central basic extension.

I have now checked this from the TYPO3 online documentation:

https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html

And here you are:

    tx_[extension key with no underscores]_[*]

This means that you are right. You can close this issue now.

**Comment by franzholz** [comment]
However there is still something missing.
The documentation should have been like this:

    tx_[extension key with no underscores]

This should be added to the TYPO3 documentation.

**Comment by romm** [comment]
Yes, thank you for the investigation. I'm not sure if the documentation is wrong about it, that's probably more the path `config.tx_formz` that is not consistent with TYPO3 recommendations.

Anyway, because of romm/formz#74 the definition handling will surely be modified, so this is not the most serious issue right now. 😉 

Thanks for the feedback, anyway!
